apiVersion: v1
kind: Service
metadata:
  name: node-web-app-service
spec:
  selector:
    app: node-web-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
